name       : mtools
version    : 4.0.21
release    : 5
source     :
    - https://ftp.gnu.org/gnu/mtools/mtools-4.0.21.tar.gz : 969d08489d73325a3acc140b66c40ea8eafd319620a9331978b14a08c6c95504
license    : GPL-3.0-or-later
component  : system.utils
summary    : A collection of utilities to access MS-DOS disks without mounting them
description: |
    Mtools is a collection of utilities to access MS-DOS disks from GNU and Unix without mounting
    them. It supports Win'95 style long file names, OS/2 Xdf disks and 2m disks (store up to 1992k
    on a high density 3 1/2 disk). In addition to file access, it supports many FAT-specific
    features: volume labels, FAT-specific file attributes (hidden, system, ...), "bad block" map
    maintenance, access to remote floppy drives, Iomega ZIP disk protection, "secure" erase,
    display of file's on-disk layout, etc.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install -j1
